### ISSUE TITLE
Missing timeout parameter

### ISSUE THREAD

**Issue by obi4wan-nkarampinas** [ZenRows/zenrows-python-sdk#5]
Is there support for timing out the requests?
I see that the underline client is from `requests` so I was wondering if you could add support for the `timeout` param. Thanks

**Comment by danielbichuetti** [comment]
@obi4wan-nkarampinas Hello!
You can send using kwargs. But before that PR #3 is merged, you need to use sync code, not async.

**Comment by shelbaz** [comment]
[@](https://github.com/ZenRows/zenrows-python-sdk/pull/6) Feel free to add to it
